server:
  addr: localhost
  port: 8000

database:
  name: $DB_NAME
  user: $DB_USER
  port: $DB_PORT
  host: "request-db"
  password: $DB_PASSWORD
  ssl: "disable"
  #$DB_SSLMODE

proxy:
  addr: 127.0.0.1
  port: 8080